# Generated by Django 5.2.9 on 2026-01-09 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField()),
                ('opciones', models.JSONField()),
                ('respuesta_correcta', models.TextField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
